# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f83127b64f5877071cb122e577b2e41a8d8dbfa03550891db5a21c4ad80e619ad9702e1c1954a06d4fec0b8de381d739425a5347356ab18aaa0e2efbdf5f23

test:
  secret_key_base: 4f418d57347e99df56a18292d46c635a12a32a194089c7574efa7603bc40166ac489e5346e4d3da88ae5d0b9876a925699a3cfc329bc4ecb63b21bd846ed90a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
